steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'me-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/resident-scheduler-be:$SHORT_SHA'
      - '.'

  # Step 2: Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'me-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/resident-scheduler-be:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
